# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-03 20:31
from __future__ import unicode_literals

import abastecimento.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Abastecimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vale', models.CharField(blank=True, max_length=50, null=True, verbose_name='Vale/Cupom')),
                ('hodometro', models.IntegerField(default=0, validators=[abastecimento.models.validate_hodometro_and_veiculo_type], verbose_name='Hod\xf4metro/Horimetro')),
                ('quantidade', models.FloatField(verbose_name='Quantidade em Litros')),
                ('valor', models.FloatField(verbose_name='Valor Pago R$')),
                ('combustivel', models.CharField(choices=[('DS5', 'DS5'), ('ALC', 'Alcool'), ('DS1', 'DS1'), ('GSA', 'Gasolina Aditivada'), ('GSC', 'Gasolina Comum'), ('ARLA', 'ARLA'), ('LUB', 'LUB')], max_length=10)),
                ('notafiscal', models.CharField(blank=True, max_length=20, null=True)),
                ('criado_date', models.DateTimeField(verbose_name='Data Abastecimento')),
                ('atualizado_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Data Abastecimento Atualizado')),
                ('observacao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cor', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Eixo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('numeroPneus', models.IntegerField(default=0, verbose_name='N\xfamero de Pneus')),
            ],
        ),
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('codigo', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=200)),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.CharField(max_length=200)),
                ('quantidadeDiaria', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('codigo', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('razaoSocial', models.CharField(max_length=200)),
                ('nomeFantasia', models.CharField(max_length=200)),
                ('cnpj', models.CharField(blank=True, max_length=20, null=True)),
                ('endereco', models.CharField(blank=True, max_length=20, null=True)),
                ('conceito', models.CharField(blank=True, max_length=20, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('criado_date', models.DateField(auto_now_add=True, verbose_name='Data Criada')),
                ('atualizado_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Data Atualizado')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ItemManutencao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('material', models.CharField(max_length=200)),
                ('tempoServico', models.IntegerField(default=0, verbose_name='Tempo em Horas')),
                ('criado_date', models.DateField(auto_now_add=True, verbose_name='Data Criada')),
                ('atualizado_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Data Atualizado')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abastecimento.Grupo')),
            ],
        ),
        migrations.CreateModel(
            name='ItemManutencaoNaoProgramado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hodometro', models.IntegerField(default=0, verbose_name='Hod\xf4metro/Horimetro')),
                ('criado_date', models.DateField(auto_now_add=True, verbose_name='Data Criada')),
                ('atualizado_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Data Atualizado')),
                ('ItemManutencao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abastecimento.ItemManutencao')),
            ],
        ),
        migrations.CreateModel(
            name='ItemManutencaoProgramado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hodometro', models.IntegerField(default=0, verbose_name='Hod\xf4metro/Horimetro')),
                ('criado_date', models.DateField(auto_now_add=True, verbose_name='Data Criada')),
                ('atualizado_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Data Atualizado')),
            ],
        ),
        migrations.CreateModel(
            name='ItemManutencaoVeiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('material', models.CharField(max_length=200)),
                ('periodoPadrao', models.IntegerField(default=0, verbose_name='Horas ou Kilometros para cada troca')),
                ('quantidade', models.IntegerField(default=0, verbose_name='Quantidade necessaria para troca')),
                ('unidade', models.CharField(blank=True, choices=[('Km', 'Hodometro'), ('Hr', 'Horimetro')], max_length=3, null=True)),
                ('tempoServico', models.IntegerField(default=0, verbose_name='Tempo de servico total')),
                ('criado_date', models.DateField(auto_now_add=True, verbose_name='Data Criada')),
                ('atualizado_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Data Atualizado')),
                ('ItemManutencao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abastecimento.ItemManutencao')),
            ],
        ),
        migrations.CreateModel(
            name='Locacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hodometroInicial', models.IntegerField(default=0, validators=[abastecimento.models.validate_hodometro_and_veiculo_type], verbose_name='Hod\xf4metro/Horimetro Inicial')),
                ('hodometroFinal', models.IntegerField(default=0, validators=[abastecimento.models.validate_hodometro_and_veiculo_type], verbose_name='Hod\xf4metro/Horimetro Inicial')),
                ('horasprodutivo', models.CharField(max_length=200, verbose_name='Horas produtivas')),
                ('horasmanutencaoPreventiva', models.CharField(max_length=200, verbose_name='Horas Manuten\xe7\xe3o preventiva')),
                ('horasmanutencaoCorretiva', models.CharField(max_length=200, verbose_name='Horas Manuten\xe7\xe3o corretiva')),
                ('observacao', models.TextField(blank=True, null=True)),
                ('data_inicio', models.DateField(auto_now_add=True, verbose_name='Data Inicio')),
                ('data_fim', models.DateField(auto_now_add=True, verbose_name='Data Fim')),
                ('criado_date', models.DateField(auto_now_add=True, verbose_name='Data Criada')),
                ('atualizado_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Data Atualizado')),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('nome', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('nome', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=200)),
                ('unidade', models.CharField(blank=True, choices=[('Km', 'Hodometro'), ('Hr', 'Horimetro')], max_length=3, null=True)),
                ('marca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='abastecimento.Marca')),
            ],
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('nome', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('status', models.CharField(default=False, max_length=200)),
                ('sairnaagenda', models.CharField(default=False, max_length=200)),
                ('criado_date', models.DateField(auto_now_add=True, verbose_name='Data Criada')),
                ('atualizado_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Data Atualizado')),
            ],
        ),
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('nome', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('cpf', models.CharField(blank=True, max_length=20, null=True)),
                ('atualizado_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Data Atualizado')),
            ],
        ),
        migrations.CreateModel(
            name='Posto',
            fields=[
                ('nome', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('cnpj', models.CharField(blank=True, max_length=20, null=True)),
                ('criado_date', models.DateField(auto_now_add=True, verbose_name='Data Criada')),
                ('atualizado_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Data Atualizado')),
                ('observacao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('codigo', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=200)),
                ('unidade', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('placa', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Placa/Codigo Interno')),
                ('tipo', models.CharField(blank=True, choices=[('PROPRIO', 'Frota pr\xf3pria'), ('TERCEIRO-SEM', 'Terceirizados sem o desconto de combust\xedvel na medi\xe7\xe3o'), ('TERCEIRO-COM', 'Terceirizados com desconto do combust\xedvel na medi\xe7\xe3o')], max_length=13, null=True)),
                ('isVeiculo', models.BooleanField(choices=[(False, 'Maquina'), (True, 'Veiculo')], default=True, verbose_name='Veiculo/Maquina ')),
                ('observacao', models.TextField(blank=True, null=True)),
                ('favorito', models.BooleanField(default=False, verbose_name='Favorito no grafico')),
                ('criado_date', models.DateField(auto_now_add=True, verbose_name='Data Criada')),
                ('atualizado_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Data Atualizado')),
                ('itensManutencao', models.ManyToManyField(to='abastecimento.ItemManutencaoVeiculo')),
            ],
        ),
        migrations.AddField(
            model_name='locacao',
            name='obra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='abastecimento.Obra', verbose_name='Obra envolvida no abastecimento'),
        ),
        migrations.AddField(
            model_name='locacao',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abastecimento.Veiculo', verbose_name='Veiculo/Equipamento'),
        ),
        migrations.AddField(
            model_name='itemmanutencaoprogramado',
            name='ItemManutencaoVeiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abastecimento.ItemManutencaoVeiculo'),
        ),
        migrations.AddField(
            model_name='itemmanutencaoprogramado',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abastecimento.Veiculo', verbose_name='Veiculo/Equipamento'),
        ),
        migrations.AddField(
            model_name='itemmanutencaonaoprogramado',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abastecimento.Veiculo', verbose_name='Veiculo/Equipamento'),
        ),
        migrations.AddField(
            model_name='abastecimento',
            name='motorista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='abastecimento.Operador', verbose_name='Motorista/Operador'),
        ),
        migrations.AddField(
            model_name='abastecimento',
            name='obra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='abastecimento.Obra', verbose_name='Obra envolvida no abastecimento'),
        ),
        migrations.AddField(
            model_name='abastecimento',
            name='posto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abastecimento.Posto', verbose_name='Posto de abastecimento'),
        ),
        migrations.AddField(
            model_name='abastecimento',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Respons\xe1vel pelo abastecimento'),
        ),
        migrations.AddField(
            model_name='abastecimento',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abastecimento.Veiculo', verbose_name='Veiculo/Equipamento'),
        ),
    ]
