# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-05 16:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Abastecimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.TextField()),
                ('ODOM', models.CharField(max_length=13)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Quantidade')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Valor')),
                ('combustivel', models.CharField(choices=[('DS5', 'DS5'), ('ALC', 'ALC'), ('DS1', 'DS1'), ('GSA', 'GSA'), ('GSC', 'GSC'), ('ARLA', 'ARLA'), ('LUB', 'LUB')], max_length=10)),
                ('notafiscal', models.CharField(max_length=13)),
                ('criado_date', models.DateTimeField(verbose_name='Data Abastecimento')),
                ('atualizado_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Data Abastecimento Atualizado')),
            ],
        ),
        migrations.CreateModel(
            name='Posto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('observacao', models.TextField()),
                ('cnpj', models.CharField(max_length=20)),
                ('criado_date', models.DateTimeField(auto_now_add=True, verbose_name='Data Criada')),
                ('atualizado_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Data Atualizado')),
            ],
        ),
        migrations.CreateModel(
            name='Vale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Valor')),
                ('numero', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='N\xfamero')),
                ('usado', models.BooleanField(default=False, verbose_name='Usado')),
                ('criado_date', models.DateTimeField(auto_now_add=True, verbose_name='Data Criada')),
                ('atualizado_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Data Atualizado')),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=7)),
                ('observacao', models.TextField()),
                ('tipo', models.CharField(choices=[('PROPRIO', 'Frota pr\xf3pria'), ('TERCEIRO-SEM', 'Terceirizados sem o desconto de combust\xedvel na medi\xe7\xe3o'), ('TERCEIRO-COM', 'Terceirizados com desconto do combust\xedvel na medi\xe7\xe3o')], max_length=13)),
                ('criado_date', models.DateTimeField(auto_now_add=True, verbose_name='Data Criada')),
                ('atualizado_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Data Atualizado')),
                ('dono', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='abastecimento',
            name='posto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abastecimento.Posto'),
        ),
        migrations.AddField(
            model_name='abastecimento',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='abastecimento',
            name='vale',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='abastecimento.Vale'),
        ),
        migrations.AddField(
            model_name='abastecimento',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abastecimento.Veiculo'),
        ),
    ]
