# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-17 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abastecimento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmanutencaonaoprogramado',
            name='valor',
            field=models.FloatField(default=0, verbose_name='Valor'),
        ),
        migrations.AddField(
            model_name='itemmanutencaoprogramado',
            name='valor',
            field=models.FloatField(default=0, verbose_name='Valor'),
        ),
        migrations.AddField(
            model_name='itemmanutencaoveiculo',
            name='valor',
            field=models.FloatField(default=0, verbose_name='Valor Em Reais'),
        ),
    ]
