# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-07 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abastecimento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='placa',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Placa/Codigo Interno'),
        ),
    ]
