# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-13 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abastecimento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='favorito',
            field=models.BooleanField(default=False, verbose_name='Favorito no grafico'),
        ),
    ]
