# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-01 19:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abastecimento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Custo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diretoOrIndireto', models.CharField(choices=[('DIRETO', 'DIRETO'), ('INDIRETO', 'INDIRETO')], max_length=10, verbose_name='tipo de custo')),
                ('hodometro', models.IntegerField(default=0, verbose_name='Hod\xf4metro/Horimetro')),
                ('valor', models.FloatField(default=0, verbose_name='Valor')),
                ('criado_date', models.DateField(blank=True, default=datetime.datetime.now, verbose_name='Data Criada')),
                ('atualizado_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Data Atualizado')),
                ('ItemManutencao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='abastecimento.ItemManutencao')),
            ],
        ),
        migrations.RemoveField(
            model_name='customanutencaonaoprogramado',
            name='ItemManutencao',
        ),
        migrations.RemoveField(
            model_name='customanutencaonaoprogramado',
            name='veiculo',
        ),
        migrations.AlterModelOptions(
            name='veiculo',
            options={'ordering': ['placa']},
        ),
        migrations.AddField(
            model_name='veiculo',
            name='horasminimas',
            field=models.FloatField(default=0, help_text='valor em horas', verbose_name='Horas minimas por dia'),
        ),
        migrations.AlterField(
            model_name='abastecimento',
            name='criado_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Data Abastecimento'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='valor',
            field=models.FloatField(help_text='valor em reais', verbose_name='Valor da hora do veiculo'),
        ),
        migrations.DeleteModel(
            name='CustoManutencaoNaoProgramado',
        ),
        migrations.AddField(
            model_name='custo',
            name='veiculo',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='abastecimento.Veiculo', verbose_name='Veiculo/Equipamento'),
        ),
    ]
