# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-03 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abastecimento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='itensManutencao',
            field=models.ManyToManyField(null=True, to='abastecimento.ItemManutencaoVeiculo'),
        ),
    ]
