# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-19 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abastecimento', '0002_auto_20161217_2234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemmanutencaoprogramado',
            old_name='ItemManutencaoVeiculo',
            new_name='itemManutencaoVeiculo',
        ),
        migrations.AddField(
            model_name='itemmanutencaoveiculo',
            name='manutencaoRealizada',
            field=models.BooleanField(choices=[(False, 'N\xe3o'), (True, 'Sim')], default=False, verbose_name='Manutencao Realizada'),
        ),
    ]
