# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-01 23:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abastecimento', '0002_auto_20170101_1924'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManutencaoRealizada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hodometro', models.IntegerField(default=0, verbose_name='Hod\xf4metro/Horimetro')),
                ('criado_date', models.DateField(blank=True, default=datetime.datetime.now, verbose_name='Data Criada')),
                ('atualizado_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Data Atualizado')),
            ],
        ),
        migrations.RemoveField(
            model_name='customanutencaoprogramado',
            name='manutencaoVeiculo',
        ),
        migrations.RemoveField(
            model_name='customanutencaoprogramado',
            name='veiculo',
        ),
        migrations.RemoveField(
            model_name='manutencaoveiculo',
            name='valor',
        ),
        migrations.AlterField(
            model_name='custo',
            name='diretoOrIndireto',
            field=models.CharField(choices=[('DIRETO', 'DIRETO'), ('INDIRETO', 'INDIRETO')], default='INDIRETO', max_length=10, verbose_name='tipo de custo'),
        ),
        migrations.DeleteModel(
            name='CustoManutencaoProgramado',
        ),
        migrations.AddField(
            model_name='manutencaorealizada',
            name='manutencaoVeiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abastecimento.ManutencaoVeiculo'),
        ),
        migrations.AddField(
            model_name='manutencaorealizada',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abastecimento.Veiculo', verbose_name='Veiculo/Equipamento'),
        ),
    ]
