# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-03 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abastecimento', '0002_auto_20161203_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='itensManutencao',
            field=models.ManyToManyField(blank=True, null=True, to='abastecimento.ItemManutencaoVeiculo'),
        ),
    ]
