# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-14 23:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abastecimento', '0002_veiculo_favorito'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('nome', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('criado_date', models.DateField(auto_now_add=True, verbose_name='Data Criada')),
                ('atualizado_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Data Atualizado')),
            ],
        ),
        migrations.AddField(
            model_name='veiculo',
            name='veiculo',
            field=models.BooleanField(choices=[(False, 'Maquina'), (True, 'Veiculo')], default=True, verbose_name='Veiculo/Maquina '),
        ),
        migrations.AddField(
            model_name='abastecimento',
            name='obra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='abastecimento.Obra', verbose_name='Obra envolvida no abastecimento'),
        ),
    ]
