# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-06 02:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abastecimento', '0002_auto_20161005_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abastecimento',
            name='ODOM',
        ),
        migrations.RemoveField(
            model_name='abastecimento',
            name='id',
        ),
        migrations.RemoveField(
            model_name='vale',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='dono',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='id',
        ),
        migrations.AddField(
            model_name='abastecimento',
            name='hodometro',
            field=models.IntegerField(default=0, verbose_name='Hod\xf4metro'),
        ),
        migrations.AddField(
            model_name='abastecimento',
            name='motorista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='abastecimento.Usuario', verbose_name='Motorista'),
        ),
        migrations.AddField(
            model_name='vale',
            name='codigo',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='C\xf3digo'),
        ),
        migrations.AlterField(
            model_name='abastecimento',
            name='notafiscal',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='abastecimento',
            name='posto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abastecimento.Posto', verbose_name='Posto de abastecimento'),
        ),
        migrations.AlterField(
            model_name='abastecimento',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abastecimento.Usuario', verbose_name='Respons\xe1vel pelo abastecimento'),
        ),
        migrations.AlterField(
            model_name='abastecimento',
            name='vale',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='abastecimento.Vale', verbose_name='Vale'),
        ),
        migrations.AlterField(
            model_name='abastecimento',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abastecimento.Veiculo', verbose_name='Veiculo'),
        ),
        migrations.AlterField(
            model_name='posto',
            name='cnpj',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vale',
            name='valor',
            field=models.FloatField(verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='placa',
            field=models.CharField(max_length=7, primary_key=True, serialize=False),
        ),
    ]
