# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-15 00:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abastecimento', '0003_auto_20161014_2044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='veiculo',
            old_name='veiculo',
            new_name='isVeiculo',
        ),
    ]
