# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-19 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abastecimento', '0003_auto_20161219_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemmanutencaoveiculo',
            name='status',
        ),
        migrations.AlterField(
            model_name='itemmanutencaoveiculo',
            name='valor',
            field=models.FloatField(default=0, help_text='esse campo s\xf3 \xe9 usado quando ocorrer a manuten\xe7\xe3o e o usuario for realizar a baixa.', verbose_name='Valor Em Reais'),
        ),
        migrations.AlterField(
            model_name='itemmanutencaoveiculo',
            name='valorAcumulado',
            field=models.IntegerField(default=0, help_text='esse valor acumula em cada locacao o valor de km ou horas acumulados para esse item de troca de manuten\xe7\xe3o', verbose_name='Horas ou Kilometros ja registrado'),
        ),
    ]
