# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-06 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abastecimento', '0003_auto_20161005_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vale',
            name='id',
        ),
        migrations.AlterField(
            model_name='vale',
            name='codigo',
            field=models.CharField(default=None, max_length=13, primary_key=True, serialize=False, verbose_name='C\xf3digo'),
            preserve_default=False,
        ),
    ]
