# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-03 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abastecimento', '0003_auto_20161203_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='sairnaagenda',
            field=models.BooleanField(choices=[(False, 'N\xe3o'), (True, 'Sim')], default=False, verbose_name='Sair na Agenda'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='status',
            field=models.BooleanField(choices=[(False, 'N\xe3o'), (True, 'Sim')], default=False, verbose_name='Status'),
        ),
    ]
