# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-09 19:30
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('abastecimento', '0003_auto_20170101_2308'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManutencaoCorretivaRealizada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('hodometro', models.IntegerField(default=0, verbose_name='Hod\xf4metro/Horimetro')),
                ('executado', models.BooleanField(choices=[(False, 'N\xe3o'), (True, 'Sim')], default=False, verbose_name='Executado')),
                ('criado_date', models.DateField(blank=True, default=datetime.datetime.now, verbose_name='Data Criada')),
                ('atualizado_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Data Atualizado')),
                ('itemManutencao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abastecimento.ItemManutencao')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abastecimento.Veiculo', verbose_name='Veiculo/Equipamento')),
            ],
        ),
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.TextField(blank=True, null=True)),
                ('fechada', models.BooleanField(choices=[(False, 'Aberta'), (True, 'Fechada')], default=False, verbose_name='Executado')),
                ('criado_date', models.DateField(blank=True, default=datetime.datetime.now, verbose_name='Data Criada')),
                ('atualizado_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Data Atualizado')),
                ('manutencaoCorretivaRealizadas', models.ManyToManyField(blank=True, to='abastecimento.ManutencaoCorretivaRealizada')),
            ],
        ),
        migrations.AddField(
            model_name='manutencaorealizada',
            name='executado',
            field=models.BooleanField(choices=[(False, 'N\xe3o'), (True, 'Sim')], default=False, verbose_name='Executado'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='manutencaoRealizadas',
            field=models.ManyToManyField(blank=True, to='abastecimento.ManutencaoRealizada'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='materiais',
            field=models.ManyToManyField(blank=True, to='abastecimento.ItemManutencao'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Respons\xe1vel pelo abastecimento'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abastecimento.Veiculo', verbose_name='Veiculo/Equipamento'),
        ),
    ]
