# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-19 23:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abastecimento', '0004_auto_20161219_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmanutencao',
            name='fornecedor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='abastecimento.Fornecedor'),
        ),
    ]
