# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-22 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abastecimento', '0004_auto_20170109_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='fechada',
            field=models.BooleanField(choices=[(False, 'Aberta'), (True, 'Fechada')], default=False, verbose_name='Fechada'),
        ),
    ]
