# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-04 00:23
from __future__ import unicode_literals

import abastecimento.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abastecimento', '0004_auto_20161203_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='hodometro',
            field=models.IntegerField(default=0, verbose_name='Hod\xf4metro/Horimetro'),
        ),
        migrations.AlterField(
            model_name='locacao',
            name='hodometroFinal',
            field=models.IntegerField(default=0, validators=[abastecimento.models.validate_hodometro_and_veiculo_type], verbose_name='Hod\xf4metro/Horimetro Final'),
        ),
        migrations.AlterField(
            model_name='locacao',
            name='horasmanutencaoCorretiva',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(8)], verbose_name='Horas Manuten\xe7\xe3o corretiva'),
        ),
        migrations.AlterField(
            model_name='locacao',
            name='horasmanutencaoPreventiva',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(8)], verbose_name='Horas Manuten\xe7\xe3o preventiva'),
        ),
        migrations.AlterField(
            model_name='locacao',
            name='horasprodutivo',
            field=models.IntegerField(default=8, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(8)], verbose_name='Horas produtivas'),
        ),
    ]
