# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-04 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abastecimento', '0005_auto_20161204_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locacao',
            name='data_fim',
            field=models.DateField(verbose_name='Data Fim'),
        ),
        migrations.AlterField(
            model_name='locacao',
            name='data_inicio',
            field=models.DateField(verbose_name='Data Inicio'),
        ),
    ]
