# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-22 22:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abastecimento', '0005_auto_20170122_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='manutencaocorretivarealizada',
            name='ordemServico',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='abastecimento.OrdemServico'),
        ),
        migrations.AddField(
            model_name='manutencaorealizada',
            name='ordemServico',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='abastecimento.OrdemServico'),
        ),
    ]
