# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-04 17:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abastecimento', '0006_auto_20161204_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='hodometro_date',
            field=models.DateField(blank=True, default=datetime.datetime.now, verbose_name='Data da atualizacao do hodometro'),
        ),
    ]
