# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-02 00:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abastecimento', '0006_auto_20170122_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemservico',
            name='materiais',
        ),
        migrations.AddField(
            model_name='manutencaocorretivarealizada',
            name='quantidade',
            field=models.IntegerField(default=0, verbose_name='Quantidade de itens'),
        ),
        migrations.AlterField(
            model_name='locacao',
            name='obra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='abastecimento.Obra', verbose_name='Obra envolvida'),
        ),
        migrations.AlterField(
            model_name='manutencaocorretivarealizada',
            name='ordemServico',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='abastecimento.OrdemServico'),
        ),
        migrations.AlterField(
            model_name='manutencaorealizada',
            name='ordemServico',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='abastecimento.OrdemServico'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='manutencaoCorretivaRealizadas',
            field=models.ManyToManyField(blank=True, to='abastecimento.ManutencaoCorretivaRealizada', verbose_name='Manutencao Corretiva'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='manutencaoRealizadas',
            field=models.ManyToManyField(blank=True, to='abastecimento.ManutencaoRealizada', verbose_name='Manutencao Programada'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Respons\xe1vel'),
        ),
    ]
