# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-15 23:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abastecimento', '0007_auto_20170702_0015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motor',
            fields=[
                ('numeroSerie', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='N\xfamero de serie')),
                ('criado_date', models.DateField(auto_now_add=True, verbose_name='Data Criada')),
                ('atualizado_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Data Atualizado')),
                ('modelo', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='abastecimento.Modelo')),
            ],
        ),
        migrations.AddField(
            model_name='manutencaoveiculo',
            name='acao',
            field=models.BooleanField(choices=[('VERIFICAR', 'Verificar'), ('TROCAR', 'Trocar'), ('LIMPAR', 'Limpar')], default=False, verbose_name='A\xe7\xe3o'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='ano',
            field=models.IntegerField(blank=True, choices=[(1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017)], default=2016, null=True, verbose_name='year'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='chassi',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Chassi'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='modelo',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='abastecimento.Modelo'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='motor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='abastecimento.Motor'),
        ),
    ]
