# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-04 19:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('abastecimento', '0007_veiculo_hodometro_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemmanutencaoveiculo',
            old_name='ItemManutencao',
            new_name='itemManutencao',
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='itensManutencao',
        ),
        migrations.AddField(
            model_name='itemmanutencaoveiculo',
            name='veiculo',
            field=models.ForeignKey(default=datetime.datetime(2016, 12, 4, 19, 39, 41, 386756, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, to='abastecimento.Veiculo', verbose_name='Veiculo/Equipamento'),
            preserve_default=False,
        ),
    ]
