# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-16 00:49
from __future__ import unicode_literals

import abastecimento.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('abastecimento', '0008_auto_20170715_2356'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locacao_cobranca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hodometro', models.IntegerField(default=0, validators=[abastecimento.models.validate_hodometro_and_veiculo_type], verbose_name='Hod\xf4metro/Horimetro')),
                ('data_inicio', models.DateField(verbose_name='Data Inicio')),
                ('data_fim', models.DateField(verbose_name='Data Fim')),
                ('criado_date', models.DateField(auto_now_add=True, verbose_name='Data Criada')),
                ('atualizado_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Data Atualizado')),
            ],
        ),
        migrations.CreateModel(
            name='Locacao_desconto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(help_text='valor em reais', verbose_name='Valor da hora do veiculo')),
                ('observacao', models.TextField(blank=True, null=True)),
                ('criado_date', models.DateField(auto_now_add=True, verbose_name='Data Criada')),
                ('atualizado_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Data Atualizado')),
                ('locacaoCobranca', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='abastecimento.Locacao_cobranca')),
            ],
        ),
        migrations.AddField(
            model_name='manutencaorealizada',
            name='estadoManutencao',
            field=models.BooleanField(choices=[('EXAMINAR', 'Examinar'), ('ANALISE', 'Em An\xe1lise'), ('AGUARDANDO', 'Aguardando'), ('ORDEM_DE_SERVICO', 'Ordem de Servi\xe7o'), ('CONCLUIDA', 'Conclu\xedda')], default='EXAMINAR', verbose_name='Estado Manutencao'),
        ),
        migrations.AddField(
            model_name='locacao_cobranca',
            name='locacaoDescontos',
            field=models.ManyToManyField(blank=True, to='abastecimento.Locacao_desconto', verbose_name='Manutencao Corretiva'),
        ),
        migrations.AddField(
            model_name='locacao_cobranca',
            name='obra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='abastecimento.Obra', verbose_name='Obra envolvida'),
        ),
        migrations.AddField(
            model_name='locacao_cobranca',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Respons\xe1vel'),
        ),
        migrations.AddField(
            model_name='locacao_cobranca',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abastecimento.Veiculo', verbose_name='Veiculo/Equipamento'),
        ),
    ]
