# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-06 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abastecimento', '0008_auto_20161005_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abastecimento',
            name='criado_date',
            field=models.DateTimeField(verbose_name='Data Abastecimento'),
        ),
    ]
