# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-16 00:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abastecimento', '0009_auto_20170716_0049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custo',
            name='ItemManutencao',
        ),
        migrations.RemoveField(
            model_name='custo',
            name='hodometro',
        ),
        migrations.AddField(
            model_name='custo',
            name='fornecedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='abastecimento.Fornecedor'),
        ),
        migrations.AddField(
            model_name='custo',
            name='notafiscal',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='custo',
            name='ordemServico',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='abastecimento.OrdemServico'),
        ),
    ]
